// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/acc/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccountApi"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回包括用户信息,token,过期时间",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.LoginResp"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/acc/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccountApi"
                ],
                "summary": "用户注册账号",
                "parameters": [
                    {
                        "description": "用户名, 昵称, 密码, 角色ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户注册账号,返回包括用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SysUserResp"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/example/Test": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExampleTest"
                ],
                "summary": "测试1",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取meta信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/example/Test1": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExampleTest"
                ],
                "summary": "测试2",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取meta信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        },
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.LoginReq": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.Register": {
            "type": "object"
        },
        "response.LoginResp": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/system.SysUser"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SysUserResp": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/system.SysUser"
                }
            }
        },
        "system.SysUser": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "appType": {
                    "type": "integer"
                },
                "auditDate": {
                    "type": "string"
                },
                "auditStatus": {
                    "type": "integer"
                },
                "auditor": {
                    "type": "string"
                },
                "createDate": {
                    "type": "string"
                },
                "createID": {
                    "type": "integer"
                },
                "creator": {
                    "type": "string"
                },
                "deptIds": {
                    "type": "string"
                },
                "deptName": {
                    "type": "string"
                },
                "dept_Id": {
                    "description": "用户登录密码",
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "enable": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "headImageUrl": {
                    "type": "string"
                },
                "isRegregisterPhone": {
                    "type": "integer"
                },
                "lastLoginDate": {
                    "type": "string"
                },
                "lastModifyPwdDate": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "modifier": {
                    "type": "string"
                },
                "modifyDate": {
                    "type": "string"
                },
                "modifyID": {
                    "type": "integer"
                },
                "orderNo": {
                    "type": "integer"
                },
                "phoneNo": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "role_Ids": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userTrueName": {
                    "type": "string"
                },
                "user_Id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "vol-gin-admin-api Swagger API接口文档",
	Description:      "vol快速开发框架基于go语言gin框架实现",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
