definitions:
  request.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  request.Register:
    properties:
      email:
        example: 电子邮箱
        type: string
      enable:
        example: int 是否启用
        type: string
      headerImg:
        example: 头像链接
        type: string
      nickName:
        example: 昵称
        type: string
      passWord:
        example: 密码
        type: string
      phone:
        example: 电话号码
        type: string
      userName:
        example: 用户名
        type: string
    type: object
  response.LoginResp:
    properties:
      expiresAt:
        type: integer
      token:
        type: string
      user:
        $ref: '#/definitions/system.SysUser'
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SysUserResp:
    properties:
      user:
        $ref: '#/definitions/system.SysUser'
    type: object
  system.SysUser:
    properties:
      address:
        type: string
      appType:
        type: integer
      auditStatus:
        type: string
      auditor:
        type: integer
      createDate:
        type: string
      createID:
        type: integer
      creator:
        type: string
      dept_Id:
        description: 用户登录密码
        type: integer
      deptIds:
        type: string
      deptName:
        type: string
      email:
        type: string
      enable:
        type: integer
      gender:
        type: integer
      headImageUrl:
        type: string
      isRegregisterPhone:
        type: integer
      lastLoginDate:
        type: string
      lastModifyPwdDate:
        type: string
      mobile:
        type: string
      modifier:
        type: string
      modifyDate:
        type: string
      modifyID:
        type: integer
      orderNo:
        type: integer
      phoneNo:
        type: string
      remark:
        type: string
      role_Ids:
        type: string
      roleName:
        type: string
      tel:
        type: string
      user_Id:
        type: integer
      userName:
        type: string
      userTrueName:
        type: string
    type: object
info:
  contact: {}
  description: vol快速开发框架基于go语言gin框架实现
  title: vol-gin-admin-api Swagger API接口文档
  version: v1.0.0
paths:
  /acc/login:
    post:
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResp'
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - Base
  /example/Test:
    get:
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取meta信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      summary: 测试1
      tags:
      - ExampleTest
  /example/Test1:
    get:
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取meta信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      summary: 测试2
      tags:
      - ExampleTest
  /user/admin_register:
    post:
      parameters:
      - description: 用户名, 昵称, 密码, 角色ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: 用户注册账号,返回包括用户信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.SysUserResp'
                msg:
                  type: string
              type: object
      summary: 用户注册账号
      tags:
      - SysUser
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
